# ----------------------------------------------------------------------
#
#    Docker compose script -- This file is part of the Power Monitoring
#    (Basic solution) distribution. It contains all the service, network
#    and volume dependencies needed to configure and document the 
#    solution on a Raspberry Pi 4b with raspbian OS version 11 (bullseye)
#    32 bits.
#
#    Copyright (C) 2022  Shoestring and University of Cambridge
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see https://www.gnu.org/licenses/.
#
# ----------------------------------------------------------------------

version: "3"

services:
   influxdb_emon:
      image: hypriot/rpi-influxdb
      ports: 
         - "8089:8086"
      container_name: influxdb
      restart: always
      environment:
         - INFLUXDB_INIT_PWD= "admin"
         - PRE_CREATE_DB= emon
      volumes:
         - ./data_store:/var/lib/influxdb
      networks:
         dial:
            ipv4_address: 172.18.0.2


   grafana_emon:
      image: grafana/grafana
      ports: 
         - "3000:3000"
      container_name: grafana
      restart: always
      volumes:
         - grafana-db:/var/lib/grafana
         - grafana-log:/var/log/grafana
         - grafana-conf:/etc/grafana
      environment:
         - GF_AUTH_DISABLE_LOGIN_FORM=true
         - GF_AUTH_ANONYMOUS_ENABLED=true
         - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
         - GF_SECURITY_ALLOW_EMBEDDING=true

      networks:
          dial:
             ipv4_address: 172.18.0.3
             
      depends_on:
           - influxdb_emon

   
   data_collection_python:
      image: read_data:v1
      container_name: read_data
      privileged: true
      restart: always
      networks:
          dial:
             ipv4_address: 172.18.0.9
      depends_on:
           - influxdb_emon


   mosquitto_emon:
       image: pascaldevink/rpi-mosquitto
       ports:
          - "1883:1883"
       container_name: mosquitto
       restart: always
       volumes:
           - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
           - ./mosquitto/data:/mosquitto/data
           - ./mosquitto/log:/mosquitto/log
       networks:
            dial:
               ipv4_address: 172.18.0.4



networks:
     dial:
        ipam:
          config:
             - subnet: 172.18.0.0/16

volumes:
     grafana-db:
        driver: local
     grafana-log:
        driver: local
     grafana-conf:
        driver: local
